name: build-and-push
on:
  push:
    tags:
      - "*"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag ghcr.io/lukejoshuapark/instant-coffee:${{ github.ref_name }} .
